apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: arbeidstiltak-visning
  namespace: pto
  labels:
    team: pto
spec:
  image: {{image}}:{{image_tag}}
  port: 80
  ingresses:
    - https://arbeidstiltak-visning.dev.intern.nav.no
  liveness:
    path: /
    initialDelay: 10
  readiness:
    path: /
    initialDelay: 10
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  env:
    - name: CORS_DOMAIN
      value: "*"
