name: Build
on: [pull_request]
env:
  NODE_VERSION: '14.x'

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{env.NODE_VERSION}}
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{env.NODE_VERSION}}
      - run: npm ci
      - run: npm run build

#  cypress-run:
#    name: Cypress run
#    runs-on: ubuntu-latest
#    timeout-minutes: 15
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#      - name: Cypress run
#        uses: cypress-io/github-action@v2
#        with:
#          browser: chrome
#          headless: true
#          start: npm start cypress:run
#          wait-on: http://localhost:3000
#          record: true

      cypress-run:
        name: Cypress run
        runs-on: ubuntu-latest
        timeout-minutes: 15
        steps:
          - name: Checkout
            uses: actions/checkout@v2
          - name: Install node
            uses: actions/setup-node@v2
            with:
              node:version: '14'
          - name: Install dependencies
            run: npm install
          - name: Cypress run
            uses: cypress-io/github-action@v2
            with:
              browser: chrome
              headless: true
              wait-on: http://localhost:3000
              start: npm start cypress:run
