name: Build
on: [pull_request]
env:
  NODE_VERSION: '14.x'

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{env.NODE_VERSION}}
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{env.NODE_VERSION}}
      - run: npm ci
      - run: npm run build

  link-to-trello:
    runs-on: ubuntu-latest
    name: Trello update
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get trello card id
        continue-on-error: true
        id: card
        uses: navikt/veilarbtrelloactions/get-card@v2.0
        with:
          key: ${{ secrets.TRELLO_KEY }}
          token: ${{ secrets.TRELLO_TOKEN }}
          board: ${{ secrets.TRELLO_BOARD_ID }}
      - name: Attach branch to card
        continue-on-error: true
        id: Attach
        uses: navikt/veilarbtrelloactions/create-attachment@v2.0
        if: ${{ steps.card.outputs.success }}
        with:
          key: ${{ secrets.TRELLO_KEY }}
          token: ${{ secrets.TRELLO_TOKEN }}
          card-id: ${{ steps.card.outputs.card-id }}
          attachment-type: branch
