name: Test, build and deploy
on: push
env:
  IMAGE_TAG: ${{ github.sha }}
  IMAGE: ghcr.io/navikt/arbeidstiltak-visning
  PRINT_PAYLOAD: true
  RESOURCE: .nais/nais.yaml
  CI: true
  TZ: Europe/Amsterdam
  NODE_VERSION: '14.x'

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/dev' && github.ref != 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{env.NODE_VERSION}}
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test

  link-to-trello:
    runs-on: ubuntu-latest
    name: Trello update
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get trello card id
        id: card
        uses: navikt/veilarbtrelloactions/get-card@v2.0
        with:
          key: ${{ secrets.TRELLO_KEY }}
          token: ${{ secrets.TRELLO_TOKEN }}
          board: ${{ secrets.TRELLO_BOARD_ID }}
      - name: Attach branch to card
        id: Attach
        uses: navikt/veilarbtrelloactions/create-attachment@v2.0
        if: ${{ steps.card.outputs.success }}
        with:
          key: ${{ secrets.TRELLO_KEY }}
          token: ${{ secrets.TRELLO_TOKEN }}
          card-id: ${{ steps.card.outputs.card-id }}
          attachment-type: branch

  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{env.NODE_VERSION}}
      - run: npm ci
      - run: npm run build

  build-docker-image:
    runs-on: ubuntu-latest
    name: Build and publish Docker image
    needs: [build, test]
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{env.NODE_VERSION}}
      - name: Build production artifact
        run: npm run build
      - name: Build and publish Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo ${GITHUB_TOKEN} | docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} --password-stdin
          echo ${GITHUB_TOKEN} | docker login ghcr.io -u ${{github.actor}} --password-stdin
          docker build -t ${IMAGE}:${IMAGE_TAG} .
          docker push ${IMAGE}:${IMAGE_TAG}

  deploy-labs:
    name: Deploy application to labs
    if: github.ref == 'refs/heads/dev'
    needs:
      - build-docker-image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: labs-gcp
          PRINT_PAYLOAD: true
          VARS: .nais/labs-gcp.yaml
          VAR: image_tag=${{env.IMAGE_TAG}}

  deploy-dev:
    name: Deploy application to dev
    if: github.ref == 'refs/heads/dev'
    needs:
      - build-docker-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          VARS: .nais/dev-gcp.yaml
          VAR: image_tag=${{env.IMAGE_TAG}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-prod:
    name: Deploy application to prod
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          VARS: .nais/prod-gcp.yaml
          VAR: image_tag=${{env.IMAGE_TAG}}
